# Generated by Django 4.1.5 on 2023-01-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podres', '0003_serviceinstance_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstance',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
