name: Django CI

on:
  push:
    branches: [ "main-development" ]
  pull_request:
    branches: [ "main-development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.1]
    env:
      PODRES_SECRET_KEY: ${{ secrets.PODRES_SECRET_KEY }}
      PODRES_DB_NAME: ${{ secrets.PODRES_DB_NAME }}
      PODRES_DB_USER: ${{ secrets.PODRES_DB_USER }}
      PODRES_DB_PASSWD: ${{ secrets.PODRES_DB_PASSWD }}
      PODRES_DB_HOST: ${{ secrets.PODRES_DB_HOST }}
      PODRES_DB_PORT: ${{ secrets.PODRES_DB_PORT }}
      PODRES_HOST1: ${{ secrets.PODRES_HOST1 }}
      PODRES_DB_ENGINE: ${{ secrets.PODRES_DB_ENGINE }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run automated tests
      run: |
        python -c "from django.conf import settings; print(settings.PODRES_DB_USER)"
        python manage.py test
    - name: Create static
      run: |
        python manage.py collectstatic --noinput
    - name: Migrate database
      run: |
        python manage.py makemigrations
        python manage.py migrate
